/// @desc
gpu_set_blendmode(blend_mode)
draw_set_color(0)
draw_set_alpha(alpha)
	draw_text_transformed(x, y, caption, 0.15, 0.15, 0)
draw_set_color(image_blend)
	draw_text_transformed(x-2, y-2, caption, 0.15, 0.15, 0)
draw_set_alpha(1)
gpu_set_blendmode(bm_normal)
draw_set_color(c_white)
